### ISSUE TITLE
Slow runtime。use i5-14600kf,it take 1.5seconds for descriptor Extract。

### ISSUE THREAD

**Issue by schwert26** [verlab/accelerated_features#84]
start_time = time.time()
descriptors1 = xfeat.get_descriptor(image1, top_k=4096)
end_time = time.time()

def get_descriptor(self, img1, top_k = None, min_cossim = -1):

	if top_k is None: top_k = self.top_k
	img1 = self.parse_input(img1)
	out1 = self.detectAndCompute(img1, top_k=top_k)[0]
	return out1['descriptors'].cpu().numpy()

it takes 1.5s for 1 img

**Comment by alaa-i** [comment]
I had same issue. I fixed it with pc format. It was caused by some dependencies but I couldnt know which.

**Comment by schwert26** [comment]
Thank you for your comment,Could you elaborate on the specific operations of pc format.?

**Comment by schwert26** [comment]
Thank you for your comment .I still have the question。Could you elaborate on the specific operations of pc format?
